//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fixed_Booking
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FixedBookingsEntities : DbContext
    {
        public FixedBookingsEntities()
            : base("name=FixedBookingsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bookings> Bookings { get; set; }
        public virtual DbSet<Fields> Fields { get; set; }
        public virtual DbSet<ReservedDates> ReservedDates { get; set; }
        public virtual DbSet<SingleBookings> SingleBookings { get; set; }
        public virtual DbSet<Sports> Sports { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
